#pragma once
extern void Add_players();
extern void Write_in_file_player();
extern bool Size_of_File();
extern void Output_players();
extern void poisk_players(int n);
extern void copy_players_from_file();
extern void Output_need_players(int i);
extern void Output_first();
extern void delete_players();
extern void edit_players();
extern void sort_players();
extern void Output_top_six();
extern void Add_staff();
extern void Write_in_file_staff();
extern void copy_staff_from_file();
extern void Output_staff();
extern void Output_need_staff(int i);
extern void Output_first_staff();
extern void delete_staff();
extern void edit_staff();
extern void poisk_staff(int n);
extern void sort_staff();
extern bool Size_of_File_staff();
extern void Add_match();
extern void Write_in_file_match();
extern void copy_match_from_file();
extern void Output_match();
extern void Output_need_match(int i);
extern void Output_first_match();
extern void delete_match();
extern void edit_match();
extern void poisk_match(int n);
extern void sort_match();
extern bool Size_of_File_match();
extern void Get_past_match();
extern  void buy_tickets();
extern void Get_future_match();